on:
  push:
    branches:
      - main

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate conventional changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          version-file: './version.json'
          output-file: false
          skip-on-empty: false
          skip-git-pull: true

      - name: Create Git release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}